//! F-002 per-action timing table: the explicit frame-data surface for every
//! intent. Numbers are the CURRENT hand-tuned values (source of truth:
//! `intent::State`); the motion-analysis pipeline (MotionBricks clip metrics)
//! replaces each row's provenance as it lands — the table is the diff
//! surface. Invariants are test-enforced; `docs/design/FRAME_DATA.md` is
//! generated from `rows()` and stale-guarded by `frame_data_doc_is_current`.

use crate::intent::intent::Intent;

/// One row of the timing table.
#[derive(Debug, Clone)]
pub struct TimingRow {
    pub action: &'static str,
    pub anim_length: u16,
    pub iasa_at: u16,
    pub iasa_on_hit: Option<u16>,
    pub iasa_on_hit_on_block: bool,
    pub interrupt_frames: &'static [u16],
    pub hitboxes: &'static str,
    pub category: &'static str,
}

const STRIKE_HITBOXES_SLASH: &str = "start=4 active=6";
const STRIKE_HITBOXES_THRUST: &str = "start=3 active=5";
const GRAB_HITBOXES: &str = "start=5 active=4";

/// The full table over the 13 canonical actions (clinch resolved separately).
pub fn rows() -> Vec<TimingRow> {
    use crate::intent::intent::{MoveDirection, StrikeVariant};
    let intents: [(&str, Intent, &'static str, &'static str); 13] = [
        (
            "Strike Slash",
            Intent::Strike {
                variant: StrikeVariant::Slash,
            },
            STRIKE_HITBOXES_SLASH,
            "Grounded",
        ),
        (
            "Strike Thrust",
            Intent::Strike {
                variant: StrikeVariant::Thrust,
            },
            STRIKE_HITBOXES_THRUST,
            "Grounded",
        ),
        ("Block", Intent::Block, "-", "Grounded"),
        ("Grab", Intent::Grab, GRAB_HITBOXES, "Grounded"),
        (
            "Dodge",
            Intent::Dodge {
                dir: MoveDirection::LateralLeft,
            },
            "-",
            "Grounded",
        ),
        (
            "Move Approach",
            Intent::move_standard(MoveDirection::Approach),
            "-",
            "Grounded",
        ),
        (
            "Move Retreat",
            Intent::move_standard(MoveDirection::Retreat),
            "-",
            "Grounded",
        ),
        (
            "Move Lateral",
            Intent::move_standard(MoveDirection::LateralRight),
            "-",
            "Grounded",
        ),
        (
            "Move Circle CCW",
            Intent::move_standard(MoveDirection::CircleCounterClockwise),
            "-",
            "Grounded",
        ),
        (
            "Move Circle CW",
            Intent::move_standard(MoveDirection::CircleClockwise),
            "-",
            "Grounded",
        ),
        ("Feint", Intent::Feint, "-", "Grounded"),
        ("Cancel", Intent::Cancel, "-", "Grounded"),
        ("Idle", Intent::Idle, "-", "Grounded"),
    ];
    intents
        .into_iter()
        .map(|(action, intent, hitboxes, category)| {
            let state = intent.state();
            TimingRow {
                action,
                anim_length: state.anim_length,
                iasa_at: state.iasa_at,
                iasa_on_hit: state.iasa_on_hit,
                iasa_on_hit_on_block: state.iasa_on_hit_on_block,
                interrupt_frames: state.interrupt_frames,
                hitboxes,
                category,
            }
        })
        .collect()
}

/// Render the table as the checked-in design doc.
pub fn render_doc() -> String {
    let mut doc = String::from(
        "# Frame Data (generated by intent::frame_data::render_doc)\n\n\
         Source of truth: `intent::State`. Provenance: hand-tuned; MotionBricks\n\
         motion-analysis replaces rows as the pipeline lands.\n\n\
         | Action | Anim | IASA | IASA-on-Hit | On-Block | Interrupts | Hitboxes | Category |\n\
         |---|---|---|---|---|---|---|---|\n",
    );
    for row in rows() {
        let iasa_hit = row
            .iasa_on_hit
            .map_or("-".to_string(), |iasa| iasa.to_string());
        doc.push_str(&format!(
            "| {} | {} | {} | {} | {} | {:?} | {} | {} |\n",
            row.action,
            row.anim_length,
            row.iasa_at,
            iasa_hit,
            row.iasa_on_hit_on_block,
            row.interrupt_frames,
            row.hitboxes,
            row.category
        ));
    }
    doc
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn timing_table_invariants_hold() {
        let table = rows();
        assert_eq!(table.len(), 13);
        for row in &table {
            assert!(row.anim_length > 0, "{}: anim_length", row.action);
            assert!(
                row.iasa_at <= row.anim_length,
                "{}: iasa_at {} must not exceed anim {}",
                row.action,
                row.iasa_at,
                row.anim_length
            );
            if let Some(iasa_hit) = row.iasa_on_hit {
                assert!(
                    iasa_hit <= row.iasa_at,
                    "{}: iasa_on_hit {iasa_hit} must not exceed iasa_at {}",
                    row.action,
                    row.iasa_at
                );
            }
            for frame in row.interrupt_frames {
                assert!(
                    *frame < row.anim_length,
                    "{}: interrupt frame {frame} outside anim",
                    row.action
                );
            }
        }
        // Measured-frame-data anchors (regression-locked).
        let slash = &table[0];
        assert_eq!(
            (slash.anim_length, slash.iasa_at, slash.iasa_on_hit),
            (22, 17, Some(5))
        );
        let thrust = &table[1];
        assert_eq!(
            (thrust.anim_length, thrust.iasa_at, thrust.iasa_on_hit),
            (18, 14, Some(4))
        );
    }

    #[test]
    fn frame_data_doc_is_current() {
        let expected = render_doc();
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/docs/design/FRAME_DATA.md");
        if std::env::var("JD_REGEN_FRAME_DATA").is_ok() {
            std::fs::write(path, &expected).expect("regen FRAME_DATA.md");
        }
        let current = std::fs::read_to_string(path).expect("docs/design/FRAME_DATA.md missing");
        assert_eq!(
            current, expected,
            "FRAME_DATA.md is stale — regenerate with JD_REGEN_FRAME_DATA=1 cargo test frame_data"
        );
    }
}
