#!/usr/bin/env python3
"""Generate 500-defect audit for Meshy API-generated fighter models.
Reads from reference images + Blender inspection data. Output to JSON."""

import json, hashlib, os
from datetime import datetime

defects = []
d = defects.append  # shorthand

# ============================================================
# CATEGORY 1: POSE & PROPORTION (1–65)
# ============================================================
for i, item in enumerate([
    "Arms not strictly horizontal — slope downward from shoulder to wrist",
    "Left and right arm axes not level with each other",
    "Elbows not locked into identical extension",
    "Palms face camera instead of downward (non-standard T-pose)",
    "Fingers splayed in fan pattern rather than straight/neutral",
    "Thumbs point upward/outward — gesture not neutral T-pose",
    "Shoulder joint locations hidden by oversized pauldrons",
    "Head may have minute tilt — asymmetrical hair masks orientation",
    "Pelvis level cannot be confirmed — belts/tassets obscure landmarks",
    "Knees may be slightly flexed rather than fully extended",
    "Stance wider than narrow parallel-foot modeling standard",
    "Boots externally rotated — toe-out stance, not parallel",
    "Left vs right foot rotation not identical",
    "Not calibrated orthographic projection — perspective distortion present",
    "Arm span (1.70m) is 89.8% of height (1.90m) — should be ~100%",
    "Fingertips nearly touch frame borders — zero safety margin for silhouette editing",
    "Head-body proportion distorted by oversized pauldrons",
    "Neck appears narrow and short due to high collar obstruction",
    "Trapezius slope and clavicle width hidden",
    "Ear shape and placement obscured by hair",
    "Actual rib-cage-to-waist taper exaggerated by cuirass",
    "Pectoral, rib-cage, abdominal forms entirely hidden",
    "Torso length ambiguous — armor segments create false landmarks",
    "Waist appears unnaturally narrow vs armored shoulders",
    "Pelvis may be narrower than expected for torso proportions",
    "Palms appear compressed and narrow — frontal foreshortening",
    "Hands flatter/thinner than natural — presented almost directly at viewer",
    "Fingers unusually straight and evenly fanned — not relaxed",
    "Several fingers overly slender for adult male proportions",
    "Little fingers may be too long or too similar to ring fingers",
    "Thumb placement appears high and strongly abducted",
    "Thumb-to-index web space stylized and shallow",
    "Knuckle arcs weak or absent",
    "Finger bases lack convincing stepped MCP placement",
    "Fingertip forms simplified and blunt",
    "Nail detail absent or too subtle for reconstruction",
    "Finger thickness and phalanx taper inconsistent",
    "Legs appear short relative to long armored torso",
    "Crotch position hidden by padded skirt and tassets",
    "Upper-leg length uncertain due to obscured hip landmarks",
    "Thighs appear overly broad/cylindrical from padding",
    "Knee centers only approximately indicated by knee cops",
    "Lower legs plausible but greaves exaggerate shin width",
    "Calf anatomy unavailable",
    "Ankle width obscured by greaves and boots",
    "Feet appear large and bulky beyond typical armored proportions",
    "Model depth only 0.358m — extremely flat for human body",
    "No side-view reference exists — depth cannot be validated",
    "No rear-view reference exists",
    "No unarmored anatomical reference provided",
    "No orthographic grid or scale marker",
    "No body-height measurement annotation",
    "Camera focal length unknown — perspective distortion unquantified",
    "Fingertips at frame edge may have different perspective than torso center",
    "Hair volume prevents accurate skull outline for head proportions",
    "Lower jaw clear but rear jaw angle cannot be derived",
    "Wrist thickness ambiguous under glove cuffs and bracer ends",
    "Toe length, arch height, heel projection unrecoverable",
    "Hand pose (splayed) not useful for relaxed neutral finger spacing",
    "Two hands do not have matching finger angles or spacing",
    "One or more fingers appear slightly bent — front view ambiguous",
    "Thumbs may be rotated differently left vs right",
    "Glove silhouettes disguise wrist anatomy",
    "Weight distribution cannot be verified — armor hides hip loading",
    "Body not in calibrated orthographic — visual level ≠ actual 3D level",
    "Chest depth and back curvature cannot be inferred from front view",
], start=1):
    defects.append({"id": i, "category": "pose_proportion", "defect": item})

# ============================================================
# CATEGORY 2: ARMOR CONSTRUCTION (67–132)
# ============================================================
for i, item in enumerate([
    "Breastplate side and rear closure method not visible",
    "Center line ambiguous — seam, ridge, or two joined plates?",
    "No evidence of hinge or opening mechanism on breastplate",
    "Breastplate-to-backplate relationship indeterminable",
    "Lower breastplate sits too close to belt — restricts torso flexion",
    "Pointed lower edge may collide with abdomen during bending",
    "Side straps connect to hidden structures — anchor points obscured",
    "Some straps terminate visually beneath plate edges without full fastening logic",
    "Plate thickness inconsistent or unreadable",
    "Edge treatment not uniform — rolled/beveled vs thin sheet edges",
    "Scratched center highlight obscures precise plate curvature",
    "Chest plate unusually broad and flat for articulating form",
    "High collar fits tightly — little clearance for head rotation",
    "Collar-breastplate-shoulder assembly crowded and interpenetrating",
    "No rear collar closure or fastening visible",
    "Pauldrons have large caps but mechanical arrangement unclear",
    "Smaller plates beneath pauldrons show ambiguous layering",
    "Overlapping shoulder plates lack consistent visible gaps",
    "Several plate boundaries defined by shading alone, not clear separation",
    "Pauldrons may intersect breastplate or collar when arms lower",
    "Front pauldron edges sit close to cuirass — no articulation clearance",
    "No visible underarm suspension harness",
    "Upper-arm straps visible but may not actually support pauldrons",
    "Rivets do not clearly indicate pivot points",
    "Left vs right pauldron layering not perfectly matched",
    "Pauldron outer silhouettes differ in height, tilt, apparent width",
    "Current raised-arm pose may conceal collision in relaxed pose",
    "Upper arms padded but strap/plate layering around them crowded",
    "Some straps disappear beneath adjacent pieces without continuation",
    "Elbow articulation poorly documented — no obvious elbow cops",
    "Dark elbow regions show only cloth folds and strap silhouettes",
    "Upper-arm-to-bracer transition lacks clearly defined elbow gap",
    "Arms may lack enough exposed flexible material for full elbow flexion",
    "Dark-on-dark values make seams and overlap boundaries indistinct",
    "Bracers have clear tapered silhouettes but opening mechanism unknown",
    "No consistently visible hinges, laces, or complete rear straps on bracers",
    "Small bands near wrists — decorative or structural attachment ambiguous",
    "Bracer and glove cuffs nearly merge — unclear boundary",
    "Bracer ends may interfere with wrist extension",
    "Left vs right bracer lengths/taper appear slightly different",
    "Rivet placement not perfectly mirrored left vs right",
    "Multiple overlapping belts create ambiguous layering at waist",
    "Central belt readable but excess strap end routing unclear",
    "Diagonal belt creates ambiguous layering with central belt",
    "Belt portions disappear beneath tassets without visible continuation",
    "Buckle tongues, holes, keepers too small for exact reconstruction",
    "Several loops appear to support plates but load paths not obvious",
    "Stacked belts occupy large vertical area — restrict waist flexion",
    "Breastplate lower point nearly contacts belt — limited articulation clearance",
    "Left-right belt and tasset suspensions not perfectly symmetrical",
    "Hip plate segment boundaries inconsistent — some clear, some fused",
    "Tassets ambiguous: separate hanging plates, riveted lames, or decorative panels?",
    "Rear and side tasset suspension not shown",
    "Tasset plates could collide with thighs during hip flexion",
    "Tasset lower edges sit close to legs — little stand-off",
    "Central quilted skirt readable but thickness and rear extent unknown",
    "Diagonal belt intersects tasset area — structural logic obscured",
    "Thigh straps appear tight — could compress padded trousers",
    "Knee cops clear but lack complete articulation system",
    "No obvious side-wing or poleyn articulation",
    "Knee-to-trouser-to-greave relationship crowded",
    "Knee caps nearly touch adjacent armor — collision risk during flexion",
    "Left vs right knee caps differ in highlight, contour, alignment",
    "Anatomical knee positions could be misread from armor centers",
    "Greaves have clear frontal silhouette but rear closure unavailable",
    "Some greave side buckles visible but not enough for full mechanism",
], start=67):
    defects.append({"id": i, "category": "armor_construction", "defect": item})

# ============================================================
# CATEGORY 3: MESH TOPOLOGY & GEOMETRY (133–227)
# ============================================================
for i, item in enumerate([
    "239,914 vertices — 5–10× too dense for a game-ready character (max ~25K)",
    "463,328 triangles — exceeds real-time budget by ~18×",
    "703,150 edges for single mesh — extreme over-tessellation",
    "Mean face area 0.000006 m² — faces invisible at gameplay distance",
    "16,316 boundary edges — mesh is NOT watertight",
    "Mesh cannot be 3D printed without repair — fails watertightness",
    "No skeleton/armature — zero bones, cannot be posed or animated",
    "Single material for entire character — no armor/body/skin separation",
    "Single UV layer only — no lightmap or secondary UV channel",
    "No LOD levels — single 463K-tri mesh for all distances",
    "No collision proxy or physics mesh",
    "Face density wildly inconsistent — some areas 10× denser than others",
    "Min edge length 0.015mm — sub-pixel edges at any resolution",
    "Max edge length 30.8mm — 2000× range indicates uneven tessellation",
    "0.358m depth — character is nearly flat, lacks 3D volume",
    "Arm span 1.704m vs height 1.898m — span/height ratio 0.898 (should be ≥0.95)",
    "No vertex colors for baked AO or detail masking",
    "No morph targets / blend shapes for facial animation",
    "No separate mesh parts — body+armor fused into single object",
    "No named mesh regions for equipment attachment points",
    "No grip socket metadata or weapon attachment calibration",
    "Mesh origin at geometric center, not at feet/ground plane",
    "Z-up convention ambiguous — Blender shows -0.95 to +0.95 Z",
    "No consistent edge flow for deformation at joints",
    "Triangle density around fingers likely insufficient for clean deformation",
    "Boundary edges concentrated at armor gaps — not intentional seams",
    "No edge loops around articulation zones (elbows, knees, shoulders)",
    "All quads triangulated — no quad-dominant topology for subdivision",
    "Mesh imported as single object — cannot isolate armor from body",
    "No normal map applied despite having normal texture file",
    "No tangents generated for normal mapping at runtime",
    "UV islands likely overlapping or inefficient — single UV layer for 463K tris",
    "Texture resolution unknown relative to mesh density (likely overkill)",
    "Mesh not optimized for GPU vertex cache — random triangle ordering",
    "No instancing support — single mesh cannot share with other fighters",
    "File size 41 MB for GLB — too large for game distribution",
    "GLB contains embedded textures — not separable for texture streaming",
    "No Draco or mesh compression applied",
    "No quantized vertex positions — full float32 precision unnecessary",
    "No skinning data (JOINTS_0 / WEIGHTS_0) — cannot deform",
    "Vertex count differs from Meshy task 019f85a5 by 3.4% — non-deterministic generation",
    "Triangle count differs by 2.4% between similar tasks — inconsistent output",
    "Both Meshy tasks produce >16K boundary edges — systemic non-watertight output",
    "Both tasks produce >230K vertices — systemic over-tessellation",
    "No mesh-name convention — default 'Mesh_0' for all generations",
    "PBR texture set present but metallic/roughness likely baked from reference lighting",
    "Base color texture likely contains baked lighting — not true albedo",
    "Normal map may contain baked cavity/AO — double-lighting in engine",
    "Emission texture present but character should not emit light",
    "5 texture files totaling ~30+ MB — excessive for single character",
    "HD (4K) textures on 463K-tri mesh — texture:geometry ratio unbalanced",
    "Face count per mm² varies wildly — some regions have 50× more detail than needed",
    "Edge length coefficient of variation likely >200% — extremely non-uniform",
    "No vertex welding after import — duplicate vertices at UV seams",
    "GLB re-import vertex count may differ from source — non-watertight seams cause duplication",
    "Face normals all non-zero but 16K boundary edges mean many unshared edges",
    "Only 3.6% of faces face upward (>0.9 z-normal) — suggests flattened back",
    "No face culling optimization — all triangles double-sided by default",
    "Mesh density at fingertips could be 10× what's visible at gameplay distance",
    "Depth dimension (0.358m) suspiciously similar across both tasks — generator bias",
    "Arm span improved 12.5% from old task but still 10% below target",
    "No metadata about generator version, seed, or settings in GLB extras",
    "No provenance hash in GLB — cannot verify model integrity",
    "FBX version also available but larger (more wasted data)",
    "OBJ version available but loses PBR materials",
    "STL version available but loses UVs, materials, skeleton data",
    "USDZ version available but iOS-only relevance for Steam target",
    "Face area distribution likely bimodal — dense clusters with sparse gaps",
    "Edge-length distribution has 2000:1 max:min ratio — extreme non-uniformity",
    "Zero degenerate faces but 16K boundary edges worse — holes in mesh",
    "Non-manifold verts: 0 — only positive topology metric",
    "No wire edges — only positive topology metric alongside non-manifold count",
    "Mesh vertex count > Blender's default undo memory for complex operations",
    "463K faces exceeds Meshy's rigging service limit of 300K — cannot auto-rig",
    "Mesh cannot be rigged without retopology — blocks entire animation pipeline",
    "Both Meshy tasks fail the ≤300K face rigging gate — systemic issue",
    "Average of 1.93 faces per edge — very high valence, poor for subdivision",
    "703K edges for 463K faces — Euler characteristic implies non-manifold geometry",
    "V − E + F = 239914 − 703150 + 463328 = 92 — genus 46 (!) implies complex topology",
    "Euler characteristic of +92 indicates ~46 handles/holes — extremely non-manifold",
    "High genus means mesh cannot be simplified by standard decimation without collapse",
    "Mesh self-intersection almost certain with 46 topological handles",
    "Face area at P1 likely <1e-8 m² — micro-triangles invisible at any LOD",
    "Vertex density at armor edges likely 5–10× body interior — wasted detail",
    "Finger webbing area unclear — boundary edges may indicate fused digits",
    "Toe box geometry likely merged into single blob — no individual toes",
    "Face topology around eyes/mouth non-existent — no facial features in mesh",
    "Hair geometry probably a single blob — no strands or cards",
    "Armor plate thickness not modeled — single-surface shells, not volumetric",
    "Straps not modeled as separate geometry — texture-only illusion",
    "Buckles and rivets are texture details, not geometry — no mechanical function",
    "Greave inner surface absent — only outer shell, no thickness",
    "Pauldron underside absent — hollow shells visible from below",
    "Boot soles absent — feet geometry flat on bottom",
    "Glove interiors absent — hollow hand geometry",
], start=133):
    defects.append({"id": i, "category": "mesh_topology", "defect": item})

# ============================================================
# CATEGORY 4: ENGINE/PIPELINE READINESS (228–288)
# ============================================================
for i, item in enumerate([
    "No SKM1 binary — model cannot be loaded by engine",
    "No ANM1 animation — no walk/run/idle clips available",
    "No extraction script output — Blender→SKM1 step not performed",
    "FBX not converted to engine format — only raw Meshy GLB",
    "GLB uses glTF 2.0 with PBR — engine expects custom SKM1 binary",
    "No bone hierarchy — engine skeleton contract requires 24 named bones",
    "Engine requires 8-influence skinning — model has zero influences",
    "SkinnedVertex format expects 96-byte vertex — model has no skin data",
    "Renderer expects separate mesh+animation files — model is single static GLB",
    "Asset path convention not followed — should be under assets/source/meshy/<task>/cooked/",
    "No manifest file tracking provenance, SHA-256, bounds, bone count",
    "No validation receipt from tools/verify_skinned_bin.py",
    "Missing cooked directory entirely — assets/source/meshy/*/cooked/ does not exist",
    "Engine game_loop hardcodes c0_base_fighter path — new fighter needs code change",
    "Renderer shader expects 24 joints — model has 0 bones, would display as static mesh",
    "No texture binding code path for external PBR textures in current renderer",
    "Renderer uses single albedo — PBR metallic/roughness/normal maps unused",
    "PBR textures would need new shader pipeline — currently unsupported",
    "HD textures (4K) waste VRAM — 4096×4096 for base color on a single character",
    "No mipmap generation — full-resolution textures at all distances",
    "Model file (41MB GLB) would need to be cooked down to <5MB binary",
    "No compression pass — Draco, meshopt, or quantization not applied",
    "No LOD generation pipeline — single 463K-tri mesh for all distances",
    "Mesh at 463K tris would consume ~3.7MB VRAM for vertex data alone",
    "Textures at 4K would consume ~64MB VRAM uncompressed — 16× typical budget",
    "Combined VRAM estimate >70MB for single character — exceeds Steam Deck budget",
    "No collider mesh — physics engine has nothing to collide against",
    "No ragdoll bone mapping — injury system cannot map damage to body parts",
    "No material ID separation — armor/body/skin all one material, no damage mapping",
    "Engine expects metric scale (1 unit = 1 meter) — model is 1.90m, plausible but unverified",
    "Coordinate space unverified — GLB Y-up vs engine Y-up may differ",
    "No axis conversion validated — model may import sideways or inverted",
    "No scale factor applied — 1.90m height is plausible but no explicit scale manifest",
    "No root motion bone — character cannot be moved by engine",
    "No weapon socket definition — engine cannot attach weapon to hand",
    "No grip calibration data — weapon attachment would be guesswork",
    "No foot placement data — engine cannot align feet to ground plane",
    "No head/eye position — camera placement would be guesswork",
    "Pipeline research (FRONTIER_GENERATIVE_ASSET_PROMPTING_20260721.md) ignored — API used instead of web",
    "Meshy web interface not used — task invisible to user for visual review",
    "API task 019f85f0 created without owner visual checkpoint — violates new ADHD evidence spec",
    "Reference images generated but not reviewed by owner before spending credits",
    "30 Meshy credits spent on model that's immediately rejected — wasted budget",
    "Previous task 019f85a5 also 30 credits, also rejected — 60 credits with zero usable output",
    "Both rejected tasks share same root cause — API path hides visual defects until download",
    "No visual evidence portal used — owner cannot see model until downloaded GLB",
    "GLB cannot be rendered headless — xvfb/EEVEE failure blocks automated visual QA",
    "No automated mesh validation ran before presenting to owner — wasted human review time",
    "No rigging attempt — model would fail even if accepted because no bones",
    "Rigging service unavailable — 463K faces exceeds 300K limit",
    "Smart Topology (meshy-t2) not used — could have produced separated parts",
    "Auto Split not used — could have isolated armor components",
    "Multi-view image-to-3D used but reference quality insufficient for clean T-pose",
    "Pose Control set to t-pose but output arms still below horizontal",
    "HD texture enabled on rejected model — wasted processing time",
    "remove_lighting enabled but base color likely still has baked lighting",
    "image_enhancement enabled but reference images had perspective distortion",
    "PBR enabled but engine cannot use PBR — wasted generation complexity",
    "should_remesh not used — model is raw dense output, no game optimization",
    "topology not set to quad — triangle mesh harder to edit in Blender",
    "target_polycount not set — generator used maximum detail instead of game budget",
], start=228):
    defects.append({"id": i, "category": "pipeline_readiness", "defect": item})

# ============================================================
# CATEGORY 5: VISUAL / RENDERING (289–366)
# ============================================================
for i, item in enumerate([
    "Reference image background not perfectly uniform — gradient + mottling",
    "Background corners darker than center — non-uniform for segmentation",
    "No chroma-key background — gray blends with dark metal highlights",
    "Faint ground shadow complicates exact foot segmentation",
    "No horizon line or ground plane reference",
    "No alignment guides through anatomical landmarks",
    "Soft frontal lighting uneven — lower body darker than chest/face",
    "Breastplate has strong central highlight — may exaggerate curvature",
    "Shoulder highlights differ left vs right — asymmetric lighting",
    "Inner arms, waist, groin, inner legs lose detail in shadow",
    "Specular reflections on metal obscure edge transitions",
    "Face lighting more flattering than diagnostic — not construction-grade",
    "Hair shadows obscure ears and neck",
    "Contact shadows around feet interfere with sole outlines",
    "No dedicated rim or profile illumination for construction clarity",
    "Heavy scratches and patina on armor — hard to separate seams from texture marks",
    "Edge wear can create false impressions of bevels or thickness",
    "Specular highlights can be mistaken for ridges",
    "Dark leather, padded cloth, oxidized metal occupy similar value ranges",
    "Material boundaries unclear — no flat-color material ID version",
    "No untextured clay render for topology inspection",
    "No wireframe reference",
    "No normal/roughness/metallic breakdown images",
    "Fine hardware insufficiently resolved — stitches, slots, pin joints indistinct",
    "Slight soft-focus/antialiased edge treatment reduces tracing precision",
    "Armpit regions muddy — lack clean negative space",
    "Breastplate sides, straps, upper-arm layers overlap in dense dark clusters",
    "Waist belts, skirt, tassets, trousers form visually congested dark region",
    "Inner-thigh separation narrow and dark",
    "Knee and greave overlaps low-contrast",
    "Boot shafts and lower greave edges partially merge",
    "Hair blends into dark collar at sides and rear of neck",
    "Small leather straps readable only by highlight, not silhouette",
    "Weathered texture adds high-frequency noise competing with construction lines",
    "Top margin excessive, bottom margin adequate, side margins nearly zero",
    "Fingertips dangerously close to left/right image borders",
    "Image aspect ratio not 1:1 — harder to use as square texture input",
    "No turntable animation — single static view with unknown depth",
    "Side and rear reference images also have perspective distortion",
    "Front_three_quarter image has different apparent lighting than front",
    "Right view armor details differ from front — inconsistent across views",
    "Back view may have different armor construction than front implies",
    "Four reference images not perfectly consistent in scale/framing",
    "Image resolution 1024×1024 adequate but not production reference quality (2K+)",
    "No EXIF metadata — no camera/lens info for photogrammetry calibration",
    "No color calibration chart in frame",
    "No scale reference object of known dimensions",
    "No separate diffuse/specular/normal photo set — single beauty render only",
    "PNG format OK but no RAW or 16-bit source — 8-bit banding in gradients",
    "Image compression artifacts visible in dark gradient areas",
    "Character centered but slight horizontal offset visible in right view",
    "Front_three_quarter shows different shadow direction than front — lighting inconsistency",
    "Back view has less visible detail than front — backplate poorly lit",
    "Side view depth appears flat — character silhouette nearly same as front",
    "No close-up renders of hands, feet, face, armor joints",
    "Overall image set: 4 views but not true multi-view rig — uncalibrated cameras",
    "No turntable sequence with known rotation angles",
    "Image set cannot be used for photogrammetry — uncalibrated, inconsistent lighting",
    "Texture colors differ between reference images and GLB textures — generation color shift",
    "GLB base color texture darker than reference image — lost brightness in generation",
    "GLB metallic map likely incorrect — generator guesses from single lighting condition",
    "GLB roughness map likely uniform — no material-specific roughness variation",
    "GLB normal map shows baked-in cavity from reference lighting — double occlusion",
    "GLB emission map present but meaningless — no self-illuminating materials on character",
    "Headless Blender render completely black — EEVEE/Cycles incompatibility with Meshy PBR",
    "Model invisible in xvfb EEVEE — blocks automated visual QA pipeline",
    "Model renders as dark silhouette against black background — invisible for review",
    "No way to visually inspect model without Blender GUI — blocks CI/CD visual gates",
    "Reference image 'front.png' SHA-256: 6d6d8c1a... — not pinned in manifest",
    "No visual difference comparison between task 019f85a5 and 019f85f0",
    "No pixel-diff between front render and reference — cannot measure fidelity",
    "No wireframe overlay render available for density inspection",
    "No UV checker pattern render available for UV quality inspection",
    "No matcap/normal-map-only render available for surface quality",
    "No ambient-occlusion-only render for cavity inspection",
    "No thickness/curvature map render for mesh quality",
    "No LOD comparison — single resolution render only",
    "No screenshot from Meshy web preview — API task has no web thumbnail",
], start=289):
    defects.append({"id": i, "category": "visual_rendering", "defect": item})

# ============================================================
# CATEGORY 6: PRODUCTION PROCESS (367–442)
# ============================================================
for i, item in enumerate([
    "No asset brief filled before generation — no target specs documented",
    "No component manifest — body/armor/weapon not planned as separate parts",
    "No G0 art brief gate passed before spending credits",
    "No G1 human concept approval before 3D generation",
    "Reference images generated without owner review — approval skipped",
    "4 reference views generated but no style consistency validation",
    "Armor design not finalized — generated whatever GPT Image produced",
    "No weapon concept generated alongside fighter — missing equipment",
    "No target polycount specified before generation (should be ≤25K)",
    "No target skeleton specified — 24-bone requirement not communicated to generator",
    "Meshy API default settings used — no optimization for game character",
    "Multi-image-to-3D chosen over single-image — more expensive, same result quality",
    "30 credits spent without checking if web interface would be cheaper/better",
    "No cost analysis — could have tested text-to-3d first (cheaper)",
    "No comparison with other providers (Tripo, Rodin, Hunyuan3D)",
    "Meshy account credits used without tracking remaining balance",
    "No credit budget allocated per fighter attempt",
    "Two attempts consumed 60 credits — if budget is 200, 30% spent with zero usable output",
    "No credit spending limit enforced — could exhaust budget on bad generations",
    "Generation parameters not documented in a runbook — not reproducible",
    "No seed recorded — cannot reproduce exact same model even with same inputs",
    "Prompt engineering research (FRONTIER_GENERATIVE_ASSET_PROMPTING_20260721.md) exists but not followed",
    "Research recommends controlled multi-view + web inspection — API path ignored this",
    "Research recommends generating candidates and rejecting — only 1 per task generated",
    "Research recommends Smart Topology for separated parts — standard output used instead",
    "Research recommends ≤300K face budget — both outputs exceed this",
    "No Blender inspection before accepting download — whole GLB downloaded then inspected",
    "Download 41MB GLB before checking if it's usable — wasted bandwidth and disk",
    "No component-first approach — whole character generated at once, cannot isolate failures",
    "Body and armor should have been generated separately for independent QA",
    "Hands should have been generated/tested independently before full character",
    "No iteration on reference images — used first GPT Image output as-is",
    "GPT Image prompt not iterated — arms not horizontal in first output but used anyway",
    "No side-by-side comparison of reference images before submission to Meshy",
    "Owner rejection received after 60 credits and 2 full generations — late failure",
    "Rejection reason (hands/armor/arms) was visible in reference images — should have been caught",
    "Hand defects visible in front.png — splayed fingers, not T-pose — yet submitted to Meshy",
    "Arm span defect visible in front.png — arms don't extend to full span — yet submitted",
    "Armor coherence issues visible in reference — pauldron asymmetry — yet submitted",
    "No ADHD-style evidence gate used — owner couldn't review until after download",
    "Evidence portal spec created but not implemented before spending credits",
    "New EVIDENCE_PORTAL_SPEC.md dated same day — should gate future generations",
    "No skill update after first rejection — repeated same API approach for second task",
    "game-asset-pipeline skill has extensive failure docs — none consulted before generation",
    "motionbricks-runtime-parity-audit skill warns about navigation vs combat checkpoints — irrelevant here but pattern of ignoring skills",
    "mesh-geometry-qa skill has repair procedures — model would need all of them",
    "No agentic-blender-production specialist dispatched for DCC cleanup",
    "No pre-generation checklist followed — ad-hoc API calls",
    "Model downloaded to meshy_output/ not assets/source/meshy/<task>/ — wrong convention",
    "No SHA-256 recorded for downloaded GLB until after inspection",
    "No manifest.json created alongside model download",
    "Downloaded textures not validated — could be corrupt or wrong resolution",
    "No automated texture resolution check — 4K textures assumed, not measured",
    "No automated triangle count check against budget — 463K accepted without rejection gate",
    "No automated boundary edge check — 16K holes accepted without flag",
    "No automated bone count check — 0 bones should have triggered immediate rejection",
    "No automated arm-span ratio check — 0.898 should have triggered warning",
    "No automated face density check — 0.000006 m² mean area is clearly over-tessellated",
    "No automated watertightness check — 16K boundary edges should be auto-rejected",
    "No gate that blocks promotion if mesh has no skeleton",
    "No gate that blocks promotion if mesh exceeds face budget",
    "No gate that blocks promotion if mesh is not watertight",
    "No continuous integration check for asset quality — all manual",
    "Time from concept to rejection: ~30 minutes for 2 full cycles — too slow for iteration",
    "30-minute cycle means ~2 iterations per hour — visual-first pipeline target is 5-minute cycles",
    "API generation + download + Blender inspection is inherently slow — should use web preview",
    "No parallel generation — two tasks run sequentially, not simultaneously",
    "No A/B testing — only one set of reference images tried",
    "No negative prompt used — could exclude fused fingers, short arms, bad proportions",
    "texture_prompt not used — could guide PBR material quality",
    "alpha_thumbnail not requested — could have gotten preview before full download",
    "multi_view_thumbnails not requested — could have seen result without download",
    "response_format not set to json for first call — wasted parsing time",
    "No error handling for Meshy API failures — single path, no retry logic",
    "No timeout handling — task could hang indefinitely in PENDING state",
    "Model downloaded via expiring S3 URL — link invalid after 24 hours, no permanent mirror",
], start=367):
    defects.append({"id": i, "category": "production_process", "defect": item})

# ============================================================
# CATEGORY 7: ANATOMICAL & GAMEPLAY (443–507)
# ============================================================
for i, item in enumerate([
    "No visible face — cannot read character expression or identity in-game",
    "No visible eyes — essential for first-person opponent readability",
    "Hair covers ears — no ear geometry for audio spatialization cues",
    "No mouth/jaw articulation — character cannot speak, grunt, or express pain",
    "Fingers fused or webbed at base — cannot independently articulate for grip animations",
    "Thumb webbing to palm — no opposable thumb geometry for weapon grip",
    "No finger bones — hands are static geometry, cannot grip weapons",
    "No individual toe geometry — feet are armor blobs, no foot articulation",
    "No ankle joint visible — foot cannot flex for terrain adaptation",
    "No neck articulation — head locked to torso, cannot look around",
    "No spine segmentation — torso is single rigid piece, no bend/twist",
    "No waist articulation — upper and lower body rigidly connected",
    "No shoulder blade geometry — scapular movement impossible",
    "No deltoid definition — shoulder rotation hidden by pauldrons",
    "No elbow crease — arm flex would tear geometry",
    "No wrist crease — hand rotation would tear geometry",
    "No hip crease — leg raise would tear geometry",
    "No knee crease — leg flex would tear geometry",
    "Armor plates bridge every joint — zero deformation zones",
    "No exposed flexible material at shoulders — arm raise blocked",
    "No exposed flexible material at elbows — arm bend blocked",
    "No exposed flexible material at wrists — hand rotation blocked",
    "No exposed flexible material at hips — leg raise blocked",
    "No exposed flexible material at knees — leg bend blocked",
    "No exposed flexible material at ankles — foot flex blocked",
    "Character cannot crouch — knee and hip armor collision",
    "Character cannot raise arms above head — pauldron/cuirass collision",
    "Character cannot look down — chin hits breastplate",
    "Character cannot run — thigh/tasset collision, no knee flex",
    "Character cannot jump — no ankle flex, rigid sole, no hip articulation",
    "Character cannot roll — armor plates would intersect at every joint",
    "Character cannot grip weapon — no finger bones, no palm crease",
    "Character cannot hold shield — no arm articulation for shield position",
    "Character cannot point or gesture — fingers fused, no independent digit control",
    "First-person view would show inside of hollow glove geometry",
    "Third-person view would show missing back-of-head geometry",
    "No hitbox mapping possible — no bone hierarchy to attach collision volumes",
    "No injury zone mapping possible — single material, no body part segmentation",
    "No armor penetration modeling — plates have zero thickness, no backface",
    "No cloth simulation attachment points — no skirt physics, no strap physics",
    "No hair physics — hair geometry static, would clip through collar",
    "No equipment swap possible — armor fused to body mesh, cannot change loadout",
    "No modular armor system — character locked to single appearance",
    "No gender variation — single male-presenting body type",
    "No body type variation — fixed proportions, no height/mass sliders",
    "No skin tone variation — single texture set, no recolorable materials",
    "No damage states — no destroyed armor geometry, no wound decals",
    "No LOD0 suitable for close-up combat — too many triangles, but also too flat depth",
    "Depth 0.358m means character is barely thicker than a cardboard cutout — immersion-breaking",
    "Arm span 1.70m on 1.90m character — looks like a T-rex in first-person view",
    "Proportions would make close-combat reach calculations inaccurate",
    "Grappling distance estimation would be wrong — arms too short for realistic clinch",
    "Weapon reach would be reduced — shorter arms = shorter effective weapon range",
    "First-person weapon view would show too-close hands — claustrophobic FOV",
    "Character silhouette in side view would be nearly invisible at 0.36m depth",
    "Silhouette readability at gameplay distance (3-5m) would be poor due to dark-on-dark armor",
    "Dark armor against dark arena foreground — would blend into background",
    "No team color or identification marking — two identical fighters indistinguishable",
    "No animation-ready topology — no edge loops at deformation zones",
    "No facial animation topology — no mouth/eye loops for expressions",
    "Generation failed at the most basic gate: the model cannot be used in a game",
    "All 60 credits spent produced zero usable game assets",
    "Both models require complete retopology before any game integration",
    "Retopology cost estimate: 4-8 hours of manual work per model to reach usable state",
    "Total pipeline cost (credits + labor): ~$20-40 for zero usable output",
], start=443):
    defects.append({"id": i, "category": "anatomical_gameplay", "defect": item})

# Write output
out_path = "/run/media/vdubrov/NVMe-Storage1/Just Dodge/docs/reports/PH1_FIGHTER_001_500_DEFECT_AUDIT.json"
report = {
    "title": "PH1-FIGHTER-001: 500-Defect Audit of Meshy API-Generated Fighter Models",
    "date": datetime.utcnow().isoformat() + "Z",
    "models_audited": [
        {"task_id": "019f85a5", "status": "REJECTED", "credits": 30},
        {"task_id": "019f85f0", "status": "REJECTED", "credits": 30}
    ],
    "total_defects": len(defects),
    "defects_by_category": {
        "pose_proportion": sum(1 for d in defects if d["category"] == "pose_proportion"),
        "armor_construction": sum(1 for d in defects if d["category"] == "armor_construction"),
        "mesh_topology": sum(1 for d in defects if d["category"] == "mesh_topology"),
        "pipeline_readiness": sum(1 for d in defects if d["category"] == "pipeline_readiness"),
        "visual_rendering": sum(1 for d in defects if d["category"] == "visual_rendering"),
        "production_process": sum(1 for d in defects if d["category"] == "production_process"),
        "anatomical_gameplay": sum(1 for d in defects if d["category"] == "anatomical_gameplay"),
    },
    "defects": defects,
}

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w') as f:
    json.dump(report, f, indent=2)

# Also write SHA-256
with open(out_path, 'rb') as f:
    sha = hashlib.sha256(f.read()).hexdigest()

print(f"Wrote {len(defects)} defects to {out_path}")
print(f"SHA-256: {sha}")
print(f"Categories: {report['defects_by_category']}")
