#!/usr/bin/env python3
"""Encode retargeted G1 clips into the primitive library."""
import argparse
import datetime
import json
import os
import re
import textwrap

import numpy as np


def encode_primitive(
    action,
    weapon,
    stance,
    source_id,
    features: np.ndarray,
    peak_idx: int,
    synthetic: bool = False,
):
    """Extract 4-frame peak window from features and emit a RON primitive snippet."""
    assert features.shape[1] == 414, features.shape
    window = features[peak_idx : peak_idx + 4]
    assert window.shape[0] == 4
    root = window[-1, :3]
    heading = np.arctan2(window[-1, 5], window[-1, 4])
    fixture_comment = " // TEST_FIXTURE_DO_NOT_SHIP" if synthetic else ""
    ron = f"""({fixture_comment}
    action: {action},
    weapon: {weapon},
    stance: {stance},
    source_id: "{source_id}",
    feature_window: {json.dumps(window.tolist())},
    root_target: (position: [{root[0]:.6f}, {root[1]:.6f}, {root[2]:.6f}], heading: {heading:.6f}),
),"""
    return ron


def _create_library(primitive_ron: str, out_path: str) -> None:
    """Create a new primitive library file containing a single primitive."""
    today = datetime.date.today().isoformat()
    library = f"""// MotionBricks primitive library for Just Dodge.
// GENERATED BY tools/encode_primitives.py — DO NOT EDIT MANUALLY.
(
    version: "{today}",
    skeleton: G1Skeleton34,
    feature_dim: 414,
    frames_per_token: 4,
    primitives: [
{textwrap.indent(primitive_ron, "        ").rstrip()}
    ],
)
"""
    parent = os.path.dirname(out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(library)


def _append_primitive(primitive_ron: str, out_path: str) -> None:
    """Append a primitive to the primitives list in an existing library file."""
    with open(out_path, "r") as f:
        lines = f.readlines()

    insert_idx = None
    for i, line in enumerate(lines):
        if re.fullmatch(r"\s*\],\s*\n?", line):
            insert_idx = i

    if insert_idx is None:
        # File exists but isn't in the expected list format; overwrite it.
        _create_library(primitive_ron, out_path)
        return

    indented = textwrap.indent(primitive_ron, "        ")
    if not indented.endswith("\n"):
        indented += "\n"
    lines.insert(insert_idx, indented)

    with open(out_path, "w") as f:
        f.writelines(lines)


def main():
    parser = argparse.ArgumentParser(description="Encode a G1 motion clip into the primitive library")
    parser.add_argument("--action", help="Action name")
    parser.add_argument("--weapon", help="Weapon name")
    parser.add_argument("--stance", help="Stance name")
    parser.add_argument("--source-id", help="Source clip identifier")
    parser.add_argument("--features", help="Path to .npy features file ([T, 414])")
    parser.add_argument("--peak", type=int, default=15, help="Frame index of the peak 4-frame window")
    parser.add_argument("--out", default="assets/data/primitives.ron", help="Output RON library path")
    parser.add_argument("--synthetic", action="store_true", help="Mark the primitive as a test fixture")
    parser.add_argument("--smoke-test", action="store_true", help="Print a dummy primitive to stdout")
    args = parser.parse_args()

    if args.smoke_test:
        dummy = np.zeros((30, 414), dtype=np.float32)
        print(encode_primitive("Strike", "Longsword", "Top", "test", dummy, 10, synthetic=args.synthetic))
        return

    required = ["action", "weapon", "stance", "source_id", "features"]
    missing = [f"--{name}" for name in required if getattr(args, name) is None]
    if missing:
        parser.error(f"the following arguments are required: {', '.join(missing)}")

    features = np.load(args.features)
    if features.ndim != 2 or features.shape[1] != 414:
        parser.error(f"expected features.shape[1] == 414, got {features.shape}")

    if args.peak < 0 or args.peak + 4 > features.shape[0]:
        parser.error(
            f"peak window [{args.peak}, {args.peak + 4}) exceeds feature bounds (T={features.shape[0]})"
        )

    primitive = encode_primitive(
        args.action,
        args.weapon,
        args.stance,
        args.source_id,
        features,
        args.peak,
        synthetic=args.synthetic,
    )

    if os.path.exists(args.out):
        _append_primitive(primitive, args.out)
    else:
        _create_library(primitive, args.out)


if __name__ == "__main__":
    main()
