#!/usr/bin/env python3
"""Encode retargeted G1 clips into the primitive library."""
import argparse
import datetime
import glob
import json
import os
import textwrap

import numpy as np
import pyron
import torch


def _build_motion_rep():
    """Build the MotionBricks GlobalRootGlobalJoints representation for normalization."""
    from motionbricks.motionlib.core.motion_reps.dual_root_global_joints import (
        GlobalRootGlobalJoints,
    )
    from motionbricks.motionlib.core.skeletons.g1 import G1Skeleton34
    from motionbricks.motionlib.core.utils.stats import Stats

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    mb_dir = os.path.abspath(os.path.join(project_root, "..", "gr00t", "motionbricks"))
    checkpoint_dir = os.path.join(mb_dir, "out")

    mb_dir = os.getenv("MB_DIR", mb_dir)
    checkpoint_dir = os.getenv("CHECKPOINT_DIR", checkpoint_dir)

    skeleton = G1Skeleton34(
        folder=os.path.join(checkpoint_dir, "motionbricks_pose", "version_1", "skeleton"),
        t_pose="capture",
    )
    stats = Stats(
        folder=os.path.join(checkpoint_dir, "motionbricks_pose", "version_1", "stats", "motion")
    )
    return GlobalRootGlobalJoints(
        name="g1skel34_dual_root_global_joints",
        stats=stats,
        skeleton=skeleton,
        fps=30,
    )


def encode_primitive(
    action,
    weapon,
    stance,
    source_id,
    features: np.ndarray,
    peak_idx: int,
):
    """Extract 4-frame peak window from features and return a primitive dict."""
    assert features.shape[1] == 414, features.shape
    window = features[peak_idx : peak_idx + 4]
    assert window.shape[0] == 4
    root = window[-1, :3]
    heading = np.arctan2(window[-1, 4], window[-1, 3])
    return {
        "action": action,
        "weapon": weapon,
        "stance": stance,
        "source_id": source_id,
        "feature_window": window.tolist(),
        "root_target": {
            "position": [float(root[0]), float(root[1]), float(root[2])],
            "heading": float(heading),
        },
    }


def _format_primitive(primitive: dict) -> str:
    """Format one primitive dict as a RON block."""
    root = primitive["root_target"]
    return f"""(
    action: {primitive['action']},
    weapon: {primitive['weapon']},
    stance: {primitive['stance']},
    source_id: {json.dumps(primitive['source_id'])},
    feature_window: {json.dumps(primitive['feature_window'])},
    root_target: (position: [{root['position'][0]:.6f}, {root['position'][1]:.6f}, {root['position'][2]:.6f}], heading: {root['heading']:.6f}),
),"""


def _format_library(primitives: list[dict], today: str | None = None) -> str:
    """Format a complete primitive library RON file."""
    if today is None:
        today = datetime.date.today().isoformat()
    blocks = (_format_primitive(p) for p in primitives)
    indented_primitives = "\n".join(textwrap.indent(b, "    ").rstrip() for b in blocks)
    return f"""// MotionBricks primitive library for Just Dodge.
// GENERATED BY tools/encode_primitives.py — DO NOT EDIT MANUALLY.
(
    version: "{today}",
    skeleton: G1Skeleton34,
    feature_dim: 414,
    frames_per_token: 4,
    primitives: [
{indented_primitives}
    ],
)
"""


def _create_library(primitive: dict, out_path: str) -> None:
    """Create a new primitive library file containing a single primitive."""
    library = _format_library([primitive])
    parent = os.path.dirname(out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(library)


def _identifier_name(value) -> str:
    """Return the lower-case name of a RON identifier/string value.

    `pyron` with `preserve_structs=True` returns identifiers as objects whose
    str() form is "Name()"; regular strings come through as-is.
    """
    name = str(value).strip()
    if name.endswith("()"):
        name = name[:-2]
    return name.lower()


def _encode_kimodo_dir(args) -> None:
    """Batch-encode Kimodo *_features.npy files into the primitive library."""
    valid_actions = {"Strike", "Block", "Thrust", "Grab", "Dodge", "Idle"}
    feature_paths = sorted(glob.glob(os.path.join(args.kimodo_dir, "*_features.npy")))
    if not feature_paths:
        print(f"[encode] no *_features.npy files found in {args.kimodo_dir}")
        return

    motion_rep = _build_motion_rep()
    out_path = args.out

    for path in feature_paths:
        basename = os.path.basename(path)
        stem = basename[: -len("_features.npy")]
        action_name = stem.split("_")[0].capitalize()

        if action_name not in valid_actions:
            print(f"[encode] skipping {basename}: unrecognized action '{action_name}'")
            continue

        features = np.load(path)
        if features.ndim != 2 or features.shape[1] != 414:
            print(f"[encode] skipping {basename}: expected shape [T, 414], got {features.shape}")
            continue

        T = features.shape[0]
        if T < 4:
            print(f"[encode] skipping {basename}: not enough frames (T={T})")
            continue

        peak_idx = min(args.peak, T - 4)
        features_t = torch.from_numpy(features)
        features_norm = motion_rep.normalize(features_t).numpy()

        primitive = encode_primitive(
            action_name,
            args.weapon,
            args.stance,
            f"kimodo_{stem}",
            features_norm,
            peak_idx,
        )

        if os.path.exists(out_path):
            _update_library(primitive, out_path, action_name, args.weapon, args.stance)
        else:
            _create_library(primitive, out_path)

        print(f"[encode] added {action_name} from {stem}")


def _update_library(
    primitive: dict,
    out_path: str,
    action: str,
    weapon: str,
    stance: str,
) -> None:
    """Replace or append a primitive in the library, rewriting the whole file."""
    with open(out_path, "r", encoding="utf-8") as f:
        text = f.read()

    data = pyron.loads(text, preserve_structs=True)
    today = data.get("version", datetime.date.today().isoformat())
    primitives = list(data.get("primitives", []))

    # Normalize pyron identifier objects back to plain strings so the
    # regenerated file uses bare RON identifiers such as `Strike`.
    for p in primitives:
        for key in ("action", "weapon", "stance"):
            if key in p:
                p[key] = str(p[key]).rstrip("()")

    target = (action.lower(), weapon.lower(), stance.lower())
    replaced = False
    for i, existing in enumerate(primitives):
        key = (
            _identifier_name(existing["action"]),
            _identifier_name(existing["weapon"]),
            _identifier_name(existing["stance"]),
        )
        if key == target:
            primitives[i] = primitive
            replaced = True
            break

    if not replaced:
        primitives.append(primitive)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(_format_library(primitives, today))


def main():
    parser = argparse.ArgumentParser(description="Encode a G1 motion clip into the primitive library")
    parser.add_argument("--action", help="Action name")
    parser.add_argument("--weapon", default="Longsword", help="Weapon name")
    parser.add_argument("--stance", default="Top", help="Stance name")
    parser.add_argument("--source-id", help="Source clip identifier")
    parser.add_argument("--features", help="Path to .npy features file ([T, 414])")
    parser.add_argument("--peak", type=int, default=15, help="Frame index of the peak 4-frame window")
    parser.add_argument("--out", default="assets/data/primitives.ron", help="Output RON library path")
    parser.add_argument("--smoke-test", action="store_true", help="Print a dummy primitive to stdout")
    parser.add_argument("--kimodo-dir", help="Directory containing Kimodo *_features.npy files to batch encode")
    args = parser.parse_args()

    if args.smoke_test:
        dummy = np.zeros((30, 414), dtype=np.float32)
        print(_format_primitive(
            encode_primitive("Strike", "Longsword", "Top", "test", dummy, 10)
        ))
        return

    if args.kimodo_dir is not None:
        _encode_kimodo_dir(args)
        return

    required = ["action", "weapon", "stance", "source_id", "features"]
    missing = [f"--{name}" for name in required if getattr(args, name) is None]
    if missing:
        parser.error(f"the following arguments are required: {', '.join(missing)}")

    features = np.load(args.features)
    if features.ndim != 2 or features.shape[1] != 414:
        parser.error(f"expected features.shape[1] == 414, got {features.shape}")

    if args.peak < 0 or args.peak + 4 > features.shape[0]:
        parser.error(
            f"peak window [{args.peak}, {args.peak + 4}) exceeds feature bounds (T={features.shape[0]})"
        )

    # Normalize features to the MotionBricks representation before storing.
    motion_rep = _build_motion_rep()
    features_t = torch.from_numpy(features)
    features_norm = motion_rep.normalize(features_t).numpy()

    primitive = encode_primitive(
        args.action,
        args.weapon,
        args.stance,
        args.source_id,
        features_norm,
        args.peak,
    )

    if os.path.exists(args.out):
        _update_library(primitive, args.out, args.action, args.weapon, args.stance)
    else:
        _create_library(primitive, args.out)


if __name__ == "__main__":
    main()
